emm_user_index:
    path:     /index
    defaults: { _controller: EMMUserBundle:User:index }
    
emm_user_aboutas:
    path:     /aboutAs/
    defaults: { _controller: EMMUserBundle:User:aboutAs }   

emm_user_entradas:
    path:     /entradas/{entradasurl}
    defaults: { _controller: EMMUserBundle:User:entradas }
    
    
emm_user_comentar:
    path:     /comentar/{entradasurl}
    defaults: { _controller: EMMUserBundle:User:comentar} 
    methods:  POST
    
emm_user_sermones:
    path:     /sermones
    defaults: { _controller: EMMUserBundle:User:sermones }     

emm_user_add:
    path:     /add
    defaults: { _controller: EMMUserBundle:User:add }

emm_user_create:
    path:     /create
    defaults: { _controller: EMMUserBundle:User:create }
    methods:  POST

emm_user_edit:
    path:     /edit/{id}
    defaults: { _controller: EMMUserBundle:User:edit }

emm_user_update:
    path:     /update/{id}
    defaults: { _controller: EMMUserBundle:User:update }
    methods:  [POST, PUT]

emm_user_view:
    path:     /view/{id}
    defaults: { _controller: EMMUserBundle:User:view }

emm_user_delete:
    path:     /delete/{id}
    defaults: { _controller: EMMUserBundle:User:delete }
    methods:  [POST, DELETE]

emm_user_subir:
    path: /subir
    defaults: { _controller: EMMUserBundle:User:subir }

emm_user_plantillas:
    path:     /plantillasVenta
    defaults: { _controller: EMMUserBundle:User:plantillasVenta}

emm_user_redirect_add:
    path: /create
    defaults:
        _controller: EMMUserBundle:User:add
        path: /add
        permanent: true
        


emm_user_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: EMMUserBundle:User:edit
        path: /edit/{id}
        permanent: true

emm_entrada_redirect_comentar:
    path: /comentar/{entradasurl}
    defaults:
        _controller: EMMUserBundle:User:edit
        path: /entrada/{entradasurl}
        permanent: true

